### ISSUE TITLE
Dropped websocket, unknown error

### ISSUE THREAD

**Issue by SirStone** [guzba/whisky#4]
Hi
I'm using your library in my project and I'm quite happy with it but I have a disconnection problem with it, sometimes it takes 1 full minute of traffic sometimes very few seconds and I receive the exception "Error receiving WebSocket frame"

Specifically the exception raised in your code at line 30-31:
```nim
if b.len != 2:
    raise newException(CatchableError, "Error receiving WebSocket frame")
```

I've already checked and it fails because it finds b.len equals to 0 but with no other info why that happened.

nim compiler in use is 2.0.0

this is my relevant code:
```nim
# connect to the server
bot.gs_ws = newWebSocket(bot.serverConnectionURL)

var whisky_msg:Option[whisky.Message]
try:
  while true:
    whisky_msg = bot.gs_ws.receiveMessage()
    if whisky_msg.isSome:
      let msg = whisky_msg.get
      case msg.kind:
      of TextMessage:
        handleMessage(bot, msg.data)
      of Ping:
        echo "[startBot] received a ping"
        discard
      else:
        echo "[startBot] received an unhandled message: ", msg.kind
        discard
    else:
      echo "[startBot] message is 'not Some'"
      discard
except CatchableError:
  echo "[startBot] ERROR: ", getCurrentExceptionMsg()
  discard
``` 

I've another piece of code that runs in **a different thread**:
```nim
while true:
    wait intentCond, intentLock
    bot.gs_ws.send(schema2json bot.intent)
``` 
you wrote:
```
Reading and writing from separate threads is currently not supported
``` 
Is this still valid even if to me is working fine until this problem pops up? Could the issue been caused by the usae of different threads?
How can I have a more detailed message what happened?

What I see is that error message and that the websocket lost the connection, so I don't know if the exception is raised because the connection is lost or vice-versa the connection is lost because of the exception.

Hope for a fix to this because your blocking library solved me a big async problem and I don't want to search for another library or go back with the previous one.

Thanks in advance

**Comment by guzba** [comment]
I believe if you receive a len of 0 it means the socket has been closed. Relevant docs: https://nim-lang.org/docs/net.html#recv%2CSocket%2Cstring%2Cint%2Cint but threading issues could be a cause too since you are using multiple threads.

> Is this still valid even if to me is working fine until this problem pops up? Could the issue been caused by the usae of different threads?

The WebSocket is a `ref object` which is not safe to use across threads. If you are 100% sure there are no ref count incs or decs it could be fine but this is entirely determined by your code and will require care and use of --expandArc. If this is wrong any number of crazy things can happen, including what you're seeing.
