### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Sznymo** [guzba/whisky#5]
Question if "whisky" works on windows ? from what I've heard mummy doesn't work very well is that true ?

**Comment by guzba** [comment]
1) Whisky work on Windows.
2) "I've heard mummy doesn't work very well is that true ?" Do you mean doesn't work well in general or just on Windows? Mummy again works just fine on Windows for development but is not an expected production OS.

Both of these questions could have been answered by just trying it.

**Comment by Sznymo** [comment]
thanks for the information just looking for a multiplatform solution :)
